/**
 * Orders API
 * This is a sample Orders API
 *
 * OpenAPI spec version: 1.0.5
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Original Ship date promised to customer. It can change based on stock availability. We need to inform customer if it changes.
 */
export class ItemEstimatedShipDateRange { 
    fromDate?: string;
    toDate?: string;
}