/**
 * Orders API
 * This is a sample Orders API
 *
 * OpenAPI spec version: 1.0.5
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Status } from '../enums/status.enum';
import { ItemEstimatedShipDateRange } from './itemEstimatedShipDateRange';
import { ItemNewEstimatedShipDateRange } from './itemNewEstimatedShipDateRange';
import { ItemSkuAttributes } from './itemSkuAttributes';

export class Item { 
    id?: number;
    name?: string;
    plan?: string;
    skuId?: string;
    skuAttributes?: ItemSkuAttributes;
    quantity?: number;
    telephoneNumber?: string;
    /**
     * Item Status
     */
    //status?: Status;
    status?: string;
    complete?: boolean;
    estimatedShipDateRange?: ItemEstimatedShipDateRange;
    newEstimatedShipDateRange?: ItemNewEstimatedShipDateRange;
    /**
     * cutomer has accepted the delay, so we can use this to avoid showing the delay shipment alert.
     */
    userAcceptedDelay?: boolean;
}
