/**
 * Orders API
 * This is a sample Orders API
 *
 * OpenAPI spec version: 1.0.5
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class Shipment { 
    id?: number;
    /**
     * List of items shipped in this shipment
     */
    items?: Array<number>;
    carrier?: string;
    trackingNumber?: string;
    trackingUrl?: string;
    estimatedDeliveryDate?: string;
    shipDate?: string;
}